language: node_js

node_js:
- '0.10'

before_install:
- sudo apt-get update -y
- sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++ -y

install:
- npm install

script:
- "./ci/bin/build"
- "./ci/bin/test"
- "./ci/bin/doc"
- npm run coverage
- npm run send-coverage
after_script: 
env:
  global:
  - secure: MFIRKBIZT7j2pMRvxhUDum70HIMQMqOGQwfxrFHg9Xc8gcCzMu/pxQQykGgwL1tEJ3pR8/sqpQvGERBKiEiLpljsvJkqlKCzdVdTKk06Co0HaoHJDhM/UaP87Gz5e1XCr7y1XDLllv2ohxQmQEtaeWze/ozcj5+hzwOSQTVdnSQ=
